name: üêß HIP

on: [workflow_call]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-hip
  cancel-in-progress: true

jobs:
  build_hip:
    name: ROCm HIP 6.3.2
    runs-on: ubuntu-24.04
    env:
      CXXFLAGS: "-Werror -Wno-deprecated-declarations -Wno-error=pass-failed"
      CMAKE_GENERATOR: Ninja
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      shell: bash
      run: |
        .github/workflows/dependencies/hip.sh 6.3.2
        .github/workflows/dependencies/dependencies_ccache.sh
    - name: Set Up Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-
    - name: build pyAMReX
      shell: bash
      run: |
        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=300M
        ccache -z

        source /etc/profile.d/rocm.sh
        hipcc --version
        which clang
        which clang++
        export CXX=$(which clang++)
        export CC=$(which clang)

        python3 -m pip install -U pip
        python3 -m pip install -U build packaging setuptools[core] wheel
        python3 -m pip install -U cmake

        cmake -S . -B build              \
            -DCMAKE_VERBOSE_MAKEFILE=ON  \
            -DpyAMReX_IPO=OFF            \
            -DAMReX_GPU_BACKEND=HIP      \
            -DAMReX_AMD_ARCH=gfx90a      \
            -DAMReX_SPACEDIM="1;2;3"
        cmake --build build --target pip_install -j 4

        ccache -s
        du -hs ~/.cache/ccache
