name: üêß Intel

on: [workflow_call]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-intel
  cancel-in-progress: true

jobs:
  tests-oneapi-sycl:
    name: oneAPI SYCL 3D
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dpcpp.sh
        .github/workflows/dependencies/dependencies_ccache.sh
    - name: Set Up Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-
    - name: Build & Install
      # mkl/rng/device/detail/mrg32k3a_impl.hpp has a number of sign-compare error
      # mkl/rng/device/detail/mrg32k3a_impl.hpp has missing braces in array-array initalization
      env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -Wnon-virtual-dtor -Wno-unused-variable -Wno-shadow"}
      run: |
        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e

        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=200M
        export CCACHE_DEPEND=1
        ccache -z

        export CC=$(which icx)
        export CXX=$(which icpx)
        python3 -m pip install -U pip setuptools[core] wheel
        python3 -m pip install -U cmake
        python3 -m pip install -U pytest mpi4py

        cmake -S . -B build               \
              -DCMAKE_BUILD_TYPE=Release  \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DBUILD_SHARED_LIBS=ON      \
              -DAMReX_GPU_BACKEND=SYCL    \
              -DAMReX_MPI=ON              \
              -DAMReX_SPACEDIM="3"
        cmake --build build --target pip_install -j 4

        ccache -s
        du -hs ~/.cache/ccache

  tests-icpx:
    name: ICPX
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dpcpp.sh
        .github/workflows/dependencies/dependencies_ccache.sh
    - name: Set Up Cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/ccache
        key: ccache-${{ github.workflow }}-${{ github.job }}-git-${{ github.sha }}
        restore-keys: |
             ccache-${{ github.workflow }}-${{ github.job }}-git-
    - name: Build & Install
      # /usr/include/c++/12/bits/stl_tempbuf.h has deprecated-declarations in 'get_temporary_buffer<std::pair<long, int>>'
      env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wunreachable-code -Wnon-virtual-dtor -Wno-deprecated-declarations"}
      run: |
        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e

        export CCACHE_COMPRESS=1
        export CCACHE_COMPRESSLEVEL=10
        export CCACHE_MAXSIZE=200M
        ccache -z

        export CC=$(which icx)
        export CXX=$(which icpx)
        python3 -m pip install -U pip setuptools[core] wheel
        python3 -m pip install -U cmake
        python3 -m pip install -U pytest mpi4py

        cmake -S . -B build               \
              -DCMAKE_BUILD_TYPE=Release  \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DAMReX_MPI=ON              \
              -DAMReX_SPACEDIM="1;2;3"
        cmake --build build --target pip_install -j 4

        ccache -s
        du -hs ~/.cache/ccache

    - name: Run tests
      run: |
        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e
        cd build
        ctest --output-on-failure
